# A list of rule codes or prefixes to enable. Prefixes can specify exact rules (like F841), entire categories (like F), or anything in between.
select = ["ALL"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
# A list of rule codes or prefixes to consider autofixable.
fixable = ["ALL"]

# A list of rule codes or prefixes to consider non-autofix-able.
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = ['out', 'Lib']

# A list of rule codes or prefixes to ignore, in addition to those specified by ignore.
ignore = ["D203", "D213"]

# A list of mappings from file pattern to rule codes or prefixes to exclude, in addition to any rules excluded by per-file-ignores.
[extend-per-file-ignores]
"tests/**/*.py" = ["S101", "PLR2004"]
"src/tutorials/**/*.py" = ["T201", "PLR2004"]
"src/mysql/**/*.py" = ['S608']
"src/beach/**/*.py" = ['S605', 'S606', 'S607']
