name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Ruff
        uses: chartboost/ruff-action@v1
      - name: Test Coverage
        run: poetry run pytest --cov=. --cov-report=lcov:coverage/lcov.info --verbose
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          debug: true
          github-token: ${{ github.token }}
