name: Validate

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install
        run: pip install poetry && poetry install
      - name: Lint
        uses: chartboost/ruff-action@v1
      - name: Test
        run: poetry run pytest --cov=. --cov-report=lcov:coverage/lcov.info --verbose
      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          debug: true
          github-token: ${{ github.token }}
